<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="OpenTelemetry" Version="1.19.1" />
    <PackageReference Include="OpenTelemetry.Exporter.InMemory" Version="1.19.1" />
    <ProjectReference Include="../../src/SeedWork.Messaging.RabbitMQ/SeedWork.Messaging.RabbitMQ.csproj" />
    <ProjectReference Include="../../src/SeedWork.Messaging.Kafka/SeedWork.Messaging.Kafka.csproj" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
